$wallpaper = /home/kamronbek/Documents/Personal/Walpapers/forest-wallpaper-3840x2160-sky-overcast-26124.jpg
$background = rgb(1A1B1A)
$foreground = rgb(F8E9D7)
$cursor = rgb(A1907E)
$color0 = rgb(454745)
$color1 = rgb(4E544F)
$color2 = rgb(736556)
$color3 = rgb(647175)
$color4 = rgb(A97F5D)
$color5 = rgb(AF8B6E)
$color6 = rgb(EAC08E)
$color7 = rgb(ECD7BE)
$color8 = rgb(A59785)
$color9 = rgb(4E544F)
$color10 = rgb(736556)
$color11 = rgb(647175)
$color12 = rgb(A97F5D)
$color13 = rgb(AF8B6E)
$color14 = rgb(EAC08E)
$color15 = rgb(ECD7BE)
$active_border = rgb(4E544F)