$wallpaper = /home/kamronbek/Documents/Personal/Walpapers/forest-wallpaper-3840x2160-sky-overcast-26124.jpg
$background = rgb(1A1B1A)
$foreground = rgb(FAEFE1)
$cursor = rgb(B9AC9E)
$color0 = rgb(747574)
$color1 = rgb(7A7F7B)
$color2 = rgb(968C80)
$color3 = rgb(8B9598)
$color4 = rgb(BF9F86)
$color5 = rgb(C3A892)
$color6 = rgb(EFD0AA)
$color7 = rgb(F1E1CE)
$color8 = rgb(BCB1A4)
$color9 = rgb(7A7F7B)
$color10 = rgb(968C80)
$color11 = rgb(8B9598)
$color12 = rgb(BF9F86)
$color13 = rgb(C3A892)
$color14 = rgb(EFD0AA)
$color15 = rgb(F1E1CE)
$active_border = rgb(7A7F7B)