$wallpaper = /home/kamronbek/Documents/new wals/forest-hill-fog.jpg
$cursor = rgb(ACACA9)
$background = rgb(050303)
$foreground = rgb(DBD2D0)
$color0 = rgb(080504)
$color1 = rgb(565C5A)
$color2 = rgb(6C6967)
$color3 = rgb(6B7472)
$color4 = rgb(807B78)
$color5 = rgb(747A78)
$color6 = rgb(7D7675)
$color7 = rgb(CEC5C3)
$color8 = rgb(898280)
$color9 = rgb(5F6764)
$color10 = rgb(7C7876)
$color11 = rgb(6D7A78)
$color12 = rgb(807772)
$color13 = rgb(7C8582)
$color14 = rgb(A69E9C)
$color15 = rgb(DEDAD9)