hl.config({ autogenerated = false })

hl.config({
    misc = {
        force_default_wallpaper = 1,
        disable_hyprland_logo   = true,
        middle_click_paste      = false
    },
})

require("colors")

require("~/.config/hypr/sections/autostart.conf")
require("sections.environment_variables")
require("sections.monitors")
require("sections.input")
require("sections.look_and_feel")
require("sections.programs")
require("sections.permissions")
require("sections.keybindings")
require("sections.windows_and_workspaces")
