source = ~/.config/hypr/colors.conf

# source = ~/.config/hypr/sections/*.conf

source = ~/.config/hypr/sections/environment_variables.conf
source = ~/.config/hypr/sections/monitors.conf
source = ~/.config/hypr/sections/input.conf
source = ~/.config/hypr/sections/look_and_feel.conf
source = ~/.config/hypr/sections/programs.conf
source = ~/.config/hypr/sections/permissions.conf
source = ~/.config/hypr/sections/keybindings.conf
source = ~/.config/hypr/sections/windows_and_workspaces.conf

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
}