require("lua.config.pack.extra.tree_sitter_manager")
require("config.pack.extra.which_key")
-- require("config.pack.extra.telescope")
-- require("config.pack.extra.fzf_lua")
-- require("config.pack.extra.oil")
-- require("config.pack.extra.lualine")
-- require("config.pack.extra.tagbar")
-- require("config.pack.extra.neo_tree")
-- require("config.pack.extra.indent_blankline")
-- require("config.pack.extra.fidget")
-- require("config.pack.extra.colorscheme")
-- require("config.pack.extra.auto_session")
-- require("config.pack.extra.alpha")
