hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprlock")
  -- hl.exec_cmd("hyprpaper")
  hl.exec_cmd("waypaper --restore")
  hl.exec_cmd("waybar")
  -- hl.exec_cmd("ashell")
  -- hl.exec_cmd("walker --gapplication-service")
  -- hl.exec_cmd("vicinae server")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  hl.exec_cmd("cursor-clip --daemon")
end)
