exec-once = $systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprlock
# exec-once = hyprpaper
exec-once = waypaper --restore
exec-once = waybar
# exec-once = ashell
# exec-once = walker --gapplication-service
exec-once = vicinae server
exec-once = wl-clip-persist --clipboard regular
exec-once = cursor-clip --daemon
