windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# opacity rules
# Set opacity to 1.0 active, 1.0 inactive and 0.8 fullscreen
windowrule = match:class firefox, opacity 1.0 override 1.0 override 1.0 override
windowrule = match:class code, opacity 1.0 override 1.0 override 1.0 override
windowrule = match:class code-insiders, opacity 1.0 override 1.0 override 1.0 override
windowrule = match:class dev.zed.Zed, opacity 1.0 override 1.0 override 1.0 override

layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.5

layerrule = match:namespace wofi, blur on
layerrule = match:namespace wofi, ignore_alpha 0.5
