[colors.primary]
background = "{{background}}"
# highlight command outputs
# color: nx time darker than cursor
foreground = "{{color6 | darken(0.1)}}"

[colors.cursor]
cursor = "{{color6}}"

[colors.selection]
text = "CellForeground"
# color: nnx time darker than cursor
background = "{{color6 | darken(0.5)}}"

[colors.normal]
black = "#000000"
# highlight prompt
# color: nx time darker than cursor
red = "{{color6 | darken(0.1)}}"
# highlight commands
# color: cursor
green = "{{color6}}"
# highlight ''/"" 
# color: cursor
yellow = "{{color6}}"
blue = "#000000"
magenta = "#000000"
# highlight paths
# color: nx time darker than cursor
cyan = "{{color6 | darken(0.1)}}"
white = "#000000"

[colors.bright]
# highlight zsh-autosuggestions
# color: 2nx time darker than cursor
black = "{{color6 | darken(0.2)}}"
red = "#d32c2c"
green = "#69cf2f"
yellow = "#caca31"
blue = "#2f50d1"
magenta = "#ffffff"
cyan = "#ffffff"
# highlight git branch and character
# color: cursor
white = "{{color6}}"
