[colors.primary]
background = "{{background}}"
# highlight command outputs
# color: nx time darker than cursor
foreground = "{{color1 | darken(0.2)}}"

[colors.cursor]
cursor = "{{color1}}"

[colors.selection]
text = "CellForeground"
# color: nnx time darker than cursor
background = "{{color1 | darken(0.5)}}"

[colors.normal]
black = "#000000"
# highlight prompt
# color: nx time darker than cursor
red = "{{color1 | darken(0.2)}}"
# highlight commands
# color: cursor
green = "{{color1}}"
# highlight ''/"" 
# color: cursor
yellow = "{{cursor}}"
# highlight --help
# color: cursor
blue = "{{color1}}"
magenta = "#000000"
# highlight paths
# color: nx time darker than cursor
cyan = "{{color1 | darken(0.4)}}"
white = "#000000"

[colors.bright]
# highlight zsh-autosuggestions
# color: 2nx time darker than cursor
black = "{{color1 | darken(0.5)}}"
red = "#d32c2c"
green = "#69cf2f"
yellow = "#caca31"
blue = "#2f50d1"
magenta = "#ffffff"
cyan = "#ffffff"
# highlight git branch and character
# color: cursor
white = "{{color1}}"
