$wallpaper = {{wallpaper}}
$background = rgb({{background | strip}})
$foreground = rgb({{foreground  | lighten(0.0) | strip}})
$cursor = rgb({{cursor  | lighten(0.0) | strip}})
$color0 = rgb({{color0  | lighten(0.0) | strip}})
$color1 = rgb({{color1  | lighten(0.0) | strip}})
$color2 = rgb({{color2  | lighten(0.0) | strip}})
$color3 = rgb({{color3  | lighten(0.0) | strip}})
$color4 = rgb({{color4  | lighten(0.0) | strip}})
$color5 = rgb({{color5  | lighten(0.0) | strip}})
$color6 = rgb({{color6  | lighten(0.0) | strip}})
$color7 = rgb({{color7  | lighten(0.0) | strip}})
$color8 = rgb({{color8  | lighten(0.0) | strip}})
$color9 = rgb({{color9  | lighten(0.0) | strip}})
$color10 = rgb({{color10  | lighten(0.0) | strip}})
$color11 = rgb({{color11  | lighten(0.0) | strip}})
$color12 = rgb({{color12  | lighten(0.0) | strip}})
$color13 = rgb({{color13  | lighten(0.0) | strip}})
$color14 = rgb({{color14  | lighten(0.0) | strip}})
$color15 = rgb({{color15  | lighten(0.0) | strip}})
$active_border = rgb({{color1 | lighten(0.0) | strip}})