[meta]
version = 1
name = "Wallust Custom Theme"
description = "A personalized theme for Vicinae"
variant = "dark"
# icon = "icons/catppuccin-mocha.png"
inherits = "vicinae-dark"

[colors.wallust]
cursor = "#1E1E2E"
background = "#1E1E2E"
foreground = "#CDD6F4"
color0 = "#89B4FA"
color1 = "#1E1E2E"
color2 = "#1E1E2E"
color3 = "#1E1E2E"
color4 = "#1E1E2E"
color5 = "#1E1E2E"
color6 = "#1E1E2E"
color7 = "#1E1E2E"
color8 = "#1E1E2E"
color9 = "#1E1E2E"
color10 = "#1E1E2E"
color11 = "#1E1E2E"
color12 = "#1E1E2E"
color13 = "#1E1E2E"
color14 = "#1E1E2E"
color15 = "#1E1E2E"

[colors.core]
accent = "colors.wallust.color0"
accent_foreground = "#ffffff"
background = "colors.wallust.background"
foreground = "colors.wallust.foreground"
secondary_background = "#242424"
border = "#2e2e2e"

[colors.main_window]
border = "#2e2e2e"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#2e2e2e"

[colors.accents]
blue = "#2f6fed"
green = "#3a9c61"
magenta = "#bc8cff"
orange = "#f0883e"
red = "#b9543b"
yellow = "#bfae78"
cyan = "#18a5b3"
purple = "#bc8cff"

# For now, shortcuts cannot have their own dedicated background
[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#e8e6e1"
danger = "#b9543b"
success = "#3a9c61"
placeholder = "#e8e6e1"
selection = { background = "#2f6fed", foreground = "#ffffff" }

[colors.text.links]
default = "#2f6fed"
visited = "#bc8cff"

[colors.input]
border = "#2e2e2e"
border_focus = "#2f6fed"
border_error = "#b9543b"

[colors.button.primary]
background = "#2e2e2e"
foreground = "#e8e6e1"
hover = { background = "#bb2e2e2e" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "#e8e6e1"
secondary_foreground = "#e8e6e1"

[colors.list.item.selection]
background = "#2e2e2e"
foreground = "#e8e6e1"
secondary_background = "#2e2e2e"
secondary_foreground = "#e8e6e1"

[colors.grid.item]
background = "#242424"
hover = { outline = "#e8e6e1" }
selection = { outline = "#e8e6e1" }

[colors.scrollbars]
background = "#2e2e2e"

[colors.loading]
bar = "#e8e6e1"     # shown right below the search bar when something is loading
spinner = "#e8e6e1" # used by dynamic toasts
