general {
  lock_cmd = hyprlock
}

listener {
  timeout = 60
  on-timeout = brightnessctl -s set 25
  on-resume = brightnessctl set 100%
}

listener {
  timeout = 300
  on-timeout = brightnessctl -s set 0
  on-resume = brightnessctl set 100%
}

listener {
  timeout = 600
  on-timeout = loginctl lock-session
  on-resume = brightnessctl set 100%
}
