[meta]
version = 1
name = "Wallust Custom Theme"
description = "A personalized theme for Vicinae"
variant = "dark"
# icon = "icons/catppuccin-mocha.png"
inherits = "vicinae-dark"

[colors.wallust]
background = "#070C18"
foreground = "#CCD7E2"
cursor = "#8D8686"
color0 = "#4D4E57"
color1 = "#6E8DAC"
color2 = "#C6643F"
color3 = "#967571"
color4 = "#837D8B"
color5 = "#75635A"
color6 = "#4B5878"
color7 = "#AEBECD"
color8 = "#7A8590"
color9 = "#6E8DAC"
color10 = "#C6643F"
color11 = "#967571"
color12 = "#837D8B"
color13 = "#75635A"
color14 = "#4B5878"
color15 = "#AEBECD"

[colors.core]
accent = "colors.wallust.color0"
accent_foreground = "#c41d1d"
background = "colors.wallust.background"
foreground = "colors.wallust.foreground"
secondary_background = "#dd2020"
border = "#e00f0f"

[colors.main_window]
border = "#cf6262"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#d81e1e"

[colors.accents]
blue = "#2f6fed"
green = "#3a9c61"
magenta = "#bc8cff"
orange = "#f0883e"
red = "#b9543b"
yellow = "#bfae78"
cyan = "#18a5b3"
purple = "#bc8cff"

# For now, shortcuts cannot have their own dedicated background
[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#e8e6e1"
danger = "#b9543b"
success = "#3a9c61"
placeholder = "#e8e6e1"
selection = { background = "#2f6fed", foreground = "#ffffff" }

[colors.text.links]
default = "#2f6fed"
visited = "#bc8cff"

[colors.input]
border = "#c93333"
border_focus = "#2f6fed"
border_error = "#b9543b"

[colors.button.primary]
background = "#c63c3c"
foreground = "#e8e6e1"
hover = { background = "#bb2e2e2e" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "#e8e6e1"
secondary_foreground = "#e8e6e1"

[colors.list.item.selection]
background = "#d01515"
foreground = "#e8e6e1"
secondary_background = "#be3939"
secondary_foreground = "#e8e6e1"

[colors.grid.item]
background = "#ba2d2d"
hover = { outline = "#e8e6e1" }
selection = { outline = "#e8e6e1" }

[colors.scrollbars]
background = "#a32525"

[colors.loading]
bar = "#e8e6e1"     # shown right below the search bar when something is loading
spinner = "#e8e6e1" # used by dynamic toasts
