
# Yazi image preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g status-keys vi

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set -g base-index 1
setw -g pane-base-index 1

set -g mouse on
set -g status-position bottom
set -g default-terminal 'tmux-256color'
set -g default-terminal "$TERM"
set -g terminal-overrides ",*:RGB"

set -sg escape-time 0
set-option -g display-time 1200
set-option -g display-panes-time 1200

# window
bind P swap-window -t -1 \; previous-window
bind N swap-window -t +1 \; next-window

# split
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L 1
bind -r C-j resize-pane -D 1
bind -r C-k resize-pane -U 1
bind -r C-l resize-pane -R 1

unbind r
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
#   set -g @resurrect-processes 'ssh psql mysql sqlite3'
# set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

set -g @plugin 'dracula/tmux'
set -g @dracula-plugins 'ssh-session network cpu-usage ram-usage'
set -g @dracula-show-left-icon session
set -g @dracula-refresh-rate 5
set -g @dracula-show-flags false
set -g @dracula-show-powerline false
set -g @dracula-transparent-powerline-bg true
set -g @dracula-border-contrast false
set -g @dracula-show-empty-plugins false
set -g @dracula-show-ssh-only-when-connected true
set -g @dracula-show-edge-icons false
set -g @dracula-left-pad ''
set -g @dracula-right-pad ''
set -g @dracula-left-icon-padding 1
# set -g @dracula-show-left-sep 
# set -g @dracula-show-right-sep 
# set -g @dracula-inverse-divider ''
set -g @dracula-cpu-usage-label ' '
set -g @dracula-ram-usage-label ' '
set -g @dracula-network-ethernet-label '󰈀 Eth'
set -g @dracula-network-offline-label '󱍢 '
set -g @dracula-network-wifi-label ' '

# source-file ~/.config/tmux/generated.conf

run -b '~/.config/tmux/plugins/tpm/tpm'

