[colors.primary]
background = '#141318'
foreground = '#e6e1e9'
 
[colors.cursor]
text = '#e6e1e9'
cursor = '#c9c4d0'
 
[colors.vi_mode_cursor]
text = '#141318'
cursor = '#cabeff'
 
[colors.search.matches]
foreground = '#48454e'
background = '#edb8cc'
 
[colors.search.focused_match]
foreground = '#48454e'
background = '#cabeff'
 
[colors.footer_bar]
foreground = '#48454e'
background = '#e6e1e9'
 
[colors.hints.start]
foreground = '#48454e'
background = '#c9c3dc'
 
[colors.hints.end]
foreground = '#48454e'
background = '#c9c3dc'
 
[colors.selection]
text = '#141318'
background = '#cabeff'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#cabeff'
yellow = '#605790'
blue = '#cabeff'
magenta = '#edb8cc'
cyan = '#c9c3dc'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
