[colors.primary]
background = '#151218'
foreground = '#ffffff'
 
[colors.cursor]
text = '#ffffff'
cursor = '#ffffff'
 
[colors.vi_mode_cursor]
text = '#151218'
cursor = '#f6ecff'
 
[colors.search.matches]
foreground = '#49454e'
background = '#ffebee'
 
[colors.search.focused_match]
foreground = '#49454e'
background = '#f6ecff'
 
[colors.footer_bar]
foreground = '#49454e'
background = '#e7e0e8'
 
[colors.hints.start]
foreground = '#49454e'
background = '#f6ecff'
 
[colors.hints.end]
foreground = '#49454e'
background = '#f6ecff'
 
[colors.selection]
text = '#151218'
background = '#f6ecff'


[colors.normal]
black = '#181818'
red = '#ffece9'
green = '#f6ecff'
yellow = '#503e76'
blue = '#f6ecff'
magenta = '#ffebee'
cyan = '#f6ecff'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
