[colors.primary]
background = "#030401"
# highlight command outputs
# color: nx time darker than cursor
foreground = "#A06054"

[colors.cursor]
cursor = "#B26B5D"

[colors.selection]
text = "CellForeground"
# color: nnx time darker than cursor
background = "#59362E"

[colors.normal]
black = "#000000"
# highlight prompt
# color: nx time darker than cursor
red = "#A06054"
# highlight commands
# color: cursor
green = "#B26B5D"
# highlight ''/"" 
# color: cursor
yellow = "#B26B5D"
# highlight --help
# color: cursor
blue = "#B26B5D"
magenta = "#000000"
# highlight paths
# color: nx time darker than cursor
cyan = "#A06054"
white = "#000000"

[colors.bright]
# highlight zsh-autosuggestions
# color: 2nx time darker than cursor
black = "#8E564A"
red = "#d32c2c"
green = "#69cf2f"
yellow = "#caca31"
blue = "#2f50d1"
magenta = "#ffffff"
cyan = "#ffffff"
# highlight git branch and character
# color: cursor
white = "#B26B5D"
