[colors.primary]
background = "#000103"
# highlight command outputs
# color: nx time darker than cursor
foreground = "#5D6268"

[colors.cursor]
cursor = "#90959B"

[colors.selection]
text = "CellForeground"
# color: nnx time darker than cursor
background = "#3A3D41"

[colors.normal]
black = "#000000"
# highlight prompt
# color: nx time darker than cursor
red = "#5D6268"
# highlight commands
# color: cursor
green = "#90959B"
# highlight ''/"" 
# color: cursor
yellow = "#99A8AE"
# highlight --help
# color: cursor
blue = "#90959B"
magenta = "#000000"
# highlight paths
# color: nx time darker than cursor
cyan = "#46494E"
white = "#000000"

[colors.bright]
# highlight zsh-autosuggestions
# color: 2nx time darker than cursor
black = "#3A3D41"
red = "#d32c2c"
green = "#69cf2f"
yellow = "#caca31"
blue = "#2f50d1"
magenta = "#ffffff"
cyan = "#ffffff"
# highlight git branch and character
# color: cursor
white = "#90959B"
