[colors.primary]
background = "#050400"
# which controls the main color, text, outputs
foreground = "#50709c"

[colors.cursor]
cursor = "#48B8A6"

[colors.selection]
text = "#ff0505"
background = "#0000ff"

[colors.normal]
black = "#f700ff"
# command is half written
red = "#256258"
# which controls command colors
green = "#48B8A6"
yellow = "#ffff00"
blue = "#ffffff"
magenta = "#ffffff"
# which controls the path
cyan = "#267164"
white = "#ffffff"

[colors.bright]
# this controls the zsh-autosuggestion remaing part
black = "#1c4b41"
red = "#6C5D3C"
green = "#94dc6f"
yellow = "#70704e"
blue = "#A13B45"
magenta = "#884900"
cyan = "#ffffff"
white = "#ffffff"
